### ISSUE TITLE
Payment gateway tripay error

### ISSUE THREAD

**Issue by fuchmi** [hotspotbilling/phpnuxbill-tripay#1]
![Screenshot 2023-03-06 195520](https://user-images.githubusercontent.com/112465990/223116450-d27392c1-b8f0-496e-8070-5ed214e0e21b.jpg)
untuk config saya rasa sudah benar, bgitu di eksekusi dari portal client eror

**Comment by ibnux** [comment]
Aktifkan telegram bot biar errornya dikirim

Juga download filenya dari halaman plugin xendit
Jangan dari release, yang file release ada bug

https://github.com/hotspotbilling/phpnuxbill-tripay

**Comment by fuchmi** [comment]
telegram bot sudah di setting, tapi gk ada pemberitahuan..

sudah di download ulang dan masih error

**Comment by ibnux** [comment]
kalo error 500 biasanya masalah di servernya.

**Comment by fuchmi** [comment]
> kalo error 500 biasanya masalah di servernya.

biasa apa yg menjadi penyebab error 500 di server ?

saya coba pindah ke server cpanel juga error

**Comment by ibnux** [comment]
Cek file error_log nya

Di cpanel biasanya muncul di sebelah index.php

**Comment by fuchmi** [comment]
`[11-Mar-2023 12:07:11 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/tripay.php:111
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): tripay_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/tripay.php on line 111
[11-Mar-2023 12:07:12 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/tripay.php:111
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): tripay_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/tripay.php on line 111
[11-Mar-2023 12:07:14 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/tripay.php:111
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): tripay_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/tripay.php on line 111
[11-Mar-2023 12:07:15 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/tripay.php:111
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): tripay_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/tripay.php on line 111
[11-Mar-2023 12:07:16 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/tripay.php:111
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): tripay_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/tripay.php on line 111
[11-Mar-2023 12:07:38 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/tripay.php:111
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): tripay_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/tripay.php on line 111
[11-Mar-2023 12:07:39 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/tripay.php:111
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): tripay_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/tripay.php on line 111
[11-Mar-2023 12:15:03 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
[11-Mar-2023 12:15:09 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
[11-Mar-2023 12:16:38 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction(Object(ORM), Object(ORM))
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
[11-Mar-2023 12:16:40 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction(Object(ORM), Object(ORM))
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
[11-Mar-2023 12:16:40 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction(Object(ORM), Object(ORM))
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
[11-Mar-2023 12:16:54 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Undefined constant PDO::MYSQL_ATTR_INIT_COMMAND in /home/rfnetmyi/bill.rfnet.my.id/system/boot.php:57
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require()
#1 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/boot.php on line 57
[11-Mar-2023 12:16:55 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Undefined constant PDO::MYSQL_ATTR_INIT_COMMAND in /home/rfnetmyi/bill.rfnet.my.id/system/boot.php:57
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require()
#1 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/boot.php on line 57
[11-Mar-2023 12:16:56 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Undefined constant PDO::MYSQL_ATTR_INIT_COMMAND in /home/rfnetmyi/bill.rfnet.my.id/system/boot.php:57
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require()
#1 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/boot.php on line 57
[11-Mar-2023 12:16:57 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Undefined constant PDO::MYSQL_ATTR_INIT_COMMAND in /home/rfnetmyi/bill.rfnet.my.id/system/boot.php:57
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require()
#1 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/boot.php on line 57
[11-Mar-2023 12:17:21 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction(Object(ORM), Object(ORM))
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
[11-Mar-2023 12:18:33 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
[11-Mar-2023 12:18:34 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
[11-Mar-2023 12:18:54 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
[11-Mar-2023 12:18:55 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
[11-Mar-2023 12:18:56 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
[11-Mar-2023 12:19:18 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
[11-Mar-2023 12:19:18 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
[11-Mar-2023 12:19:19 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
[11-Mar-2023 12:19:22 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
[11-Mar-2023 12:19:23 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
[11-Mar-2023 12:33:38 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
[11-Mar-2023 12:33:39 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function sendTelegram() in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php:104
Stack trace:
#0 /home/rfnetmyi/bill.rfnet.my.id/system/controllers/order.php(171): duitku_create_transaction()
#1 /home/rfnetmyi/bill.rfnet.my.id/system/boot.php(296): include('/home/rfnetmyi/...')
#2 /home/rfnetmyi/bill.rfnet.my.id/index.php(6): require('/home/rfnetmyi/...')
#3 {main}
  thrown in /home/rfnetmyi/bill.rfnet.my.id/system/paymentgateway/duitku.php on line 104
`

**Comment by ibnux** [comment]
Nah ini
Jadi ketahuan

Saya ada perubahan kemarin soal notifikasi user saat Expired
Jadi pengaruh ke plugin. 

Saya update dulu bentar

**Comment by ibnux** [comment]
Download ulang pluginnya

Atau update phpmixbill nya

Sudah saya perbaiki
